### ISSUE TITLE
Indicate failed purchase better

### ISSUE THREAD

**Issue by ConcernedHobbit** [TKOaly/rv-rust-frontend#2]
Currently a failed purchase prints out text that is quickly hidden by the help text block (see #1)

Failed purchase should be clearly distinct from other actions' feedback to grab the user's attention.

An example would be a large ASCII text with instructions that stays on the screen for some seconds.

The user should not be able to log out with enter/RFID while the indication is on screen, to avoid a scenario of scan+immediate logout causing the user to miss the indication.

**Comment by ArktinenKarpalo** [comment]
Partially fixed by adding beeps 4d3fb369aa48ee9a9e334945eaac9e513b87febb and timegate after failed purchase 87a2f426f8a2c0f97c8f01476af44bc2c8736a64

**Comment by ConcernedHobbit** [comment]
Seems good if #1 is fixed, beeps added (although this is not as inclusive) and the timegate. The red text is more obvious this way :)

**Comment by ConcernedHobbit** [comment]
![image](https://github.com/user-attachments/assets/c2185c5a-4818-49cf-b518-b4b523ca39c5)
seems good to me :D
