### ISSUE TITLE
Shorten deposit "banktransfer" input

### ISSUE THREAD

**Issue by ConcernedHobbit** [TKOaly/rv-rust-frontend#5]
When depositing through bank transfer, the user has to type in `banktransfer` (as opposed to `cash`).

- Make `banktransfer` shorter, such as `bank`
- Add options to use `c` and `b` as shortcuts for users who deposit small amounts often

**Comment by ArktinenKarpalo** [comment]
Shortened confirmation to `bank` see d17c659.

Shortcut sounds easy to use accidentally and if requiring explicit confirmation one could just write the whole word instead. User-specific options to do this sound complicated so won't implement them for now. Feel free to open a new issue if the shortcut is critical.
