### ISSUE TITLE
Some bug in buy-in margin calculations

### ISSUE THREAD

**Issue by ArktinenKarpalo** [TKOaly/rv-rust-frontend#8]
reported by @Tuupertunut

**Comment by Tuupertunut** [comment]
Adding a box of 50 x sukulaku with buy price 5,99€, the UI offers 6,00€ as the default sell price and claims that it has a 5% margin.

**Comment by ArktinenKarpalo** [comment]
Sounds like rounding issues with low cost products  as `floor(5.99/50)=0.11` and  `ceil(0.11*1.05)=0.12` and `50*0.12=6.0`.

As prices are stored as integer cents, fix is to always ceil cents up whenever converting from floats.
This of course results in a margin of 8.3% in this case, but that is inevitable with low cost products.

**Comment by Tuupertunut** [comment]
As boxes don't really have a price, only products do, would it be better to just show the old price and suggested sell price as product prices instead of box prices.

**Comment by ArktinenKarpalo** [comment]
Should implement margin calculations in frontend properly (e.g. with fixed-point arithmetic)

> As boxes don't really have a price, only products do, would it be better to just show the old price and suggested sell price as product prices instead of box prices.

This is also a good idea

**Comment by ArktinenKarpalo** [comment]
Bugs fixed in e975cb4
